"""The app's icon, resolved once for every window and the tray.

There is exactly one icon asset — ``assets/icon.ico``, generated by
``tools/make_icon.py`` — and it is the same file the ``.exe``, the installer, the
Start-menu shortcut and the website favicon show. Loading it here rather than
re-drawing a glyph in code is the point: a second hand-drawn tray icon is a
second thing to keep in sync, and it drifted once already (a microphone glyph in
the tray against a waveform mark everywhere else).

Qt is imported at module scope, so — like every other module under
``rekounts/ui`` — this must only be imported *after* the speech model exists.
See the import-order note in ``rekounts/__main__.py``.
"""

import logging
import sys
from pathlib import Path

from PySide6 import QtCore, QtGui

log = logging.getLogger(__name__)

# Windows groups taskbar buttons, and picks the icon shown on them, by
# AppUserModelID. Without an explicit one, a from-source run is "python.exe" and
# shows the interpreter's icon no matter what Qt sets. The frozen build gets its
# own identity from the .exe, but setting the same string in both keeps a
# pinned taskbar shortcut pointing at one app rather than two.
APP_USER_MODEL_ID = "RekreateDigital.Rekounts"

_ICON_RELATIVE = Path("assets") / "icon.ico"


def icon_path() -> Path | None:
    """Absolute path to ``assets/icon.ico``, or None if it is missing.

    PyInstaller unpacks bundled data under ``sys._MEIPASS`` (``_internal\\`` in a
    onedir build), so the frozen app and a source checkout look in different
    places for the same file.
    """
    if getattr(sys, "frozen", False):
        base = Path(getattr(sys, "_MEIPASS", Path(sys.executable).parent))
    else:
        base = Path(__file__).resolve().parent.parent.parent
    candidate = base / _ICON_RELATIVE
    return candidate if candidate.is_file() else None


def _fallback_icon() -> QtGui.QIcon:
    """The mark drawn in code, for when the asset cannot be loaded.

    Only a safety net — a broken or missing .ico should degrade to a recognisable
    icon rather than to Qt's blank default, which in the tray means an invisible
    icon the user cannot right-click. Deliberately the simplest possible echo of
    the real mark (four bars on a charcoal tile); ``tools/make_icon.py`` remains
    the source of the real thing.
    """
    size = 64
    pix = QtGui.QPixmap(size, size)
    pix.fill(QtGui.QColor(0, 0, 0, 0))
    painter = QtGui.QPainter(pix)
    painter.setRenderHint(QtGui.QPainter.Antialiasing)
    painter.setBrush(QtGui.QColor("#1a1c22"))
    painter.setPen(QtGui.QPen(QtGui.QColor("#3a3e48"), 2))
    painter.drawRoundedRect(QtCore.QRectF(1, 1, size - 2, size - 2), 18, 18)
    painter.setBrush(QtGui.QColor("#e8eaed"))
    painter.setPen(QtCore.Qt.NoPen)
    for x, y, w, h in ((16, 26, 5, 12), (26, 18, 5, 28), (36, 22, 5, 20),
                       (46, 28, 5, 8)):
        painter.drawRoundedRect(QtCore.QRectF(x, y, w, h), w / 2, w / 2)
    painter.end()
    return QtGui.QIcon(pix)


def app_icon() -> QtGui.QIcon:
    """The Rekounts icon, with every size the .ico carries.

    Not cached: a QIcon must not outlive the QGuiApplication that owns its
    pixmaps, and callers ask for this a handful of times at startup.
    """
    path = icon_path()
    if path is not None:
        icon = QtGui.QIcon(str(path))
        if not icon.isNull():
            return icon
        log.warning("icon asset at %s could not be loaded by Qt", path)
    else:
        log.warning("icon asset %s not found; drawing the fallback mark",
                    _ICON_RELATIVE)
    return _fallback_icon()


def set_app_user_model_id(app_id: str = APP_USER_MODEL_ID) -> bool:
    """Tell Windows which app this process is. True if it took.

    Best-effort by design: it is cosmetic (taskbar grouping and the taskbar
    button's icon), it is Windows-only, and it must never be able to stop the app
    from starting.
    """
    if not sys.platform.startswith("win"):
        return False
    try:
        import ctypes  # noqa: PLC0415 (Windows-only, and only worth paying for here)
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(app_id)
        return True
    except Exception as e:                                   # pragma: no cover
        log.debug("could not set AppUserModelID: %s", e)
        return False
