# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Rekounts on macOS (groundwork — NOT yet verified on
real hardware; see MACOS-TESTING.md and docs/macos-packaging.md).

Produces dist/Rekounts.app — a menu-bar (tray) app with no Dock icon:

  * LSUIElement=1: agent app — no Dock tile, no menu bar takeover; the app
    lives in the status bar, exactly like the Windows tray build.
  * NSMicrophoneUsageDescription: REQUIRED — without it macOS kills the
    process outright the first time the mic is opened (no prompt, no error).
  * The Whisper model is NOT bundled — it downloads once on first run to
    ~/Library/Application Support/Rekounts/models/<name>, exactly like the
    source build (see rekounts/models.py).

Import-order landmine (see rekounts/__main__.py): Qt must not load before the
Whisper model, or ctranslate2's and Qt's OpenMP runtimes collide. The frozen
app preserves this because it runs the same __main__.py.

Build (on a Mac):  .venv/bin/python -m PyInstaller --clean Rekounts-macos.spec

Signing/notarization are deliberately NOT attempted here — they need the
owner's Apple Developer account. The full procedure is documented in
docs/macos-packaging.md.
"""
import os
import re

from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = [], [], []

# The official icon, resolved at runtime by rekounts/ui/branding.py under
# sys._MEIPASS — without this the frozen app falls back to the code-drawn
# mark and the official waveform icon silently disappears from the mac tray.
datas += [(os.path.join("assets", "icon.ico"), "assets")]
# The .icns is the BUNDLE icon (see the note on `icon=` below). PyInstaller reads
# it at build time, not from inside the bundle, so it is NOT in datas — shipping
# it as a data file would only bloat the app with a second copy.


def _read_version() -> str:
    src = open(os.path.join("rekounts", "__init__.py"), encoding="utf-8").read()
    m = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', src, re.M)
    if not m:
        raise SystemExit("Could not find __version__ in rekounts/__init__.py")
    return m.group(1)


_VERSION = _read_version()

# Native / data-heavy deps: bundle their dylibs, data files (the silero VAD
# model, PortAudio) and submodules wholesale so nothing is missed.
for _pkg in ("ctranslate2", "faster_whisper", "onnxruntime", "av",
             "sounddevice", "_sounddevice_data", "tokenizers", "huggingface_hub"):
    _d, _b, _h = collect_all(_pkg)
    datas += _d
    binaries += _b
    hiddenimports += _h

a = Analysis(
    ["rekounts/__main__.py"],
    pathex=["."],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports + ["rekounts"],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        # CPU-only build: keep CUDA/GPU stacks out.
        "nvidia", "torch", "triton", "tensorflow", "jax",
        # Dev/test-only or unused at runtime.
        "pytest", "_pytest", "setuptools", "pip",
        "tkinter",
        # Qt modules the app never touches (only QtCore/QtGui/QtWidgets).
        "PySide6.QtQml", "PySide6.QtQuick", "PySide6.Qt3DCore",
        "PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets",
        "PySide6.QtMultimedia", "PySide6.QtCharts",
        "PySide6.QtDataVisualization", "PySide6.QtWebSockets",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Rekounts",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,        # build arch = host arch; universal2 needs fat wheels
    codesign_identity=None,  # unsigned groundwork build; see docs/macos-packaging.md
    # Left None on purpose: this spec produces an UNSIGNED app. When the owner's
    # Apple Developer account exists, signing happens as its own codesign step
    # (docs/macos-packaging.md) using packaging/entitlements.plist — which is
    # written and reviewed, just never yet run.
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="Rekounts",
)

app = BUNDLE(
    coll,
    name="Rekounts.app",
    # The bundle icon — Finder, the Dock's force-quit panel, About. It must be a
    # real .icns; PyInstaller silently ignores a .ico here, which is why this was
    # None. Generated by tools/make_icon.py from the same mark as the .ico, and
    # committed: writing an .icns needs no Mac (see the format note in that file),
    # so it does not belong in the hardware pass.
    icon=os.path.join("assets", "icon.icns"),
    bundle_identifier="com.rekreatedigital.rekounts",
    version=_VERSION,
    info_plist={
        # Agent app: menu-bar only, no Dock icon — the macOS analogue of the
        # Windows tray-only build.
        "LSUIElement": True,
        # REQUIRED: without this key macOS terminates the app the moment the
        # microphone is opened, with no prompt and no catchable error.
        "NSMicrophoneUsageDescription":
            "Rekounts records your voice only while you hold the dictation "
            "hotkey, transcribes it locally on this Mac, and never sends "
            "audio anywhere.",
        "NSHumanReadableCopyright":
            "Copyright (C) 2026 Rekreate Digital. GPL-3.0.",
        # UNVERIFIED against a real build. Note the tension found on 2026-07-25:
        # on Apple Silicon, `pip install -r requirements.txt` resolves an
        # onnxruntime wheel tagged macosx_14_0_arm64 (macOS 14+). pip backtracks
        # to an older onnxruntime on 12-13, so a build made there uses a version
        # nothing has tested. Either raise this to 14.0 or test on 12 before any
        # download ships — see docs/macos-one-hour.md.
        "LSMinimumSystemVersion": "12.0",
        "NSHighResolutionCapable": True,
    },
)
